#! /bin/bash

SESSION=$1

if [[ $SESSION != '' ]]; then
	tmux new-session -d -s "$SESSION"

	CONF="/home/matt/.tmux/confs/$SESSION.conf"
else
	tmux new-session -d
	CONF="$PWD/.tmuxxer"
fi

echo "Using config file $CONF"

if [[ -f $CONF ]]; then
	echo "sourcing $CONF"
	tmux source-file $CONF
else
	echo "file does not exist: $CONF"
	exit 1
fi

tmux select-window -t 0
tmux attach -t "$SESSION"
